name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      working-directory: docs
      run: npm i
    - name: Build docs
      working-directory: docs
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.2.5
      with:
        BRANCH: gh-pages
        FOLDER: docs/build